// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH7muUmDWe27MRw6jXLEksj72Xt2bQnfs',
    appId: '1:25373116138:web:b820dc9a80319df4d7b993',
    messagingSenderId: '25373116138',
    projectId: 'wrytte-app',
    authDomain: 'wrytte-app.firebaseapp.com',
    storageBucket: 'wrytte-app.firebasestorage.app',
    measurementId: 'G-0BEJ15R238',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCjdeDzzfo0xjpGjIeJ6QGMoiJjspuwIo',
    appId: '1:25373116138:android:32be54f6566a8a85d7b993',
    messagingSenderId: '25373116138',
    projectId: 'wrytte-app',
    storageBucket: 'wrytte-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdVX3erUU7n26Lh-qboVpH-QySwjfXJ8w',
    appId: '1:25373116138:ios:87d7a26b01d3ab7dd7b993',
    messagingSenderId: '25373116138',
    projectId: 'wrytte-app',
    storageBucket: 'wrytte-app.firebasestorage.app',
    iosBundleId: 'com.example.wrytte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdVX3erUU7n26Lh-qboVpH-QySwjfXJ8w',
    appId: '1:25373116138:ios:87d7a26b01d3ab7dd7b993',
    messagingSenderId: '25373116138',
    projectId: 'wrytte-app',
    storageBucket: 'wrytte-app.firebasestorage.app',
    iosBundleId: 'com.example.wrytte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH7muUmDWe27MRw6jXLEksj72Xt2bQnfs',
    appId: '1:25373116138:web:2dbc97af3e468350d7b993',
    messagingSenderId: '25373116138',
    projectId: 'wrytte-app',
    authDomain: 'wrytte-app.firebaseapp.com',
    storageBucket: 'wrytte-app.firebasestorage.app',
    measurementId: 'G-DLEDQ7GRS9',
  );
}
