// Country model + full dataset (ISO alpha-2 + dial code + emoji flag).
class Country {
  final String name;
  final String isoCode;
  final String dialCode;
  final String flag;
  const Country({
    required this.name,
    required this.isoCode,
    required this.dialCode,
    required this.flag,
  });

  Map<String, dynamic> toJson() => {
    'name': name,
    'isoCode': isoCode,
    'dialCode': dialCode,
    'flag': flag,
  };
}

// Utility to build emoji flag from ISO code (if you want to generate on the fly)
// String flagEmoji(String iso) => String.fromCharCodes(iso.toUpperCase().codeUnits
//     .map((c) => 0x1F1E6 - 65 + c));

const List<Country> countries = [
  Country(name: 'Afghanistan', isoCode: 'AF', dialCode: '93', flag: '🇦🇫'),
  Country(name: 'Albania', isoCode: 'AL', dialCode: '355', flag: '🇦🇱'),
  Country(name: 'Algeria', isoCode: 'DZ', dialCode: '213', flag: '🇩🇿'),
  Country(
    name: 'American Samoa',
    isoCode: 'AS',
    dialCode: '1684',
    flag: '🇦🇸',
  ),
  Country(name: 'Andorra', isoCode: 'AD', dialCode: '376', flag: '🇦🇩'),
  Country(name: 'Angola', isoCode: 'AO', dialCode: '244', flag: '🇦🇴'),
  Country(name: 'Anguilla', isoCode: 'AI', dialCode: '1264', flag: '🇦🇮'),
  Country(
    name: 'Antigua & Barbuda',
    isoCode: 'AG',
    dialCode: '1268',
    flag: '🇦🇬',
  ),
  Country(name: 'Argentina', isoCode: 'AR', dialCode: '54', flag: '🇦🇷'),
  Country(name: 'Armenia', isoCode: 'AM', dialCode: '374', flag: '🇦🇲'),
  Country(name: 'Aruba', isoCode: 'AW', dialCode: '297', flag: '🇦🇼'),
  Country(name: 'Australia', isoCode: 'AU', dialCode: '61', flag: '🇦🇺'),
  Country(name: 'Austria', isoCode: 'AT', dialCode: '43', flag: '🇦🇹'),
  Country(name: 'Azerbaijan', isoCode: 'AZ', dialCode: '994', flag: '🇦🇿'),
  Country(name: 'Bahamas', isoCode: 'BS', dialCode: '1242', flag: '🇧🇸'),
  Country(name: 'Bahrain', isoCode: 'BH', dialCode: '973', flag: '🇧🇭'),
  Country(name: 'Bangladesh', isoCode: 'BD', dialCode: '880', flag: '🇧🇩'),
  Country(name: 'Barbados', isoCode: 'BB', dialCode: '1246', flag: '🇧🇧'),
  Country(name: 'Belarus', isoCode: 'BY', dialCode: '375', flag: '🇧🇾'),
  Country(name: 'Belgium', isoCode: 'BE', dialCode: '32', flag: '🇧🇪'),
  Country(name: 'Belize', isoCode: 'BZ', dialCode: '501', flag: '🇧🇿'),
  Country(name: 'Benin', isoCode: 'BJ', dialCode: '229', flag: '🇧🇯'),
  Country(name: 'Bermuda', isoCode: 'BM', dialCode: '1441', flag: '🇧🇲'),
  Country(name: 'Bhutan', isoCode: 'BT', dialCode: '975', flag: '🇧🇹'),
  Country(name: 'Bolivia', isoCode: 'BO', dialCode: '591', flag: '🇧🇴'),
  Country(
    name: 'Bosnia & Herzegovina',
    isoCode: 'BA',
    dialCode: '387',
    flag: '🇧🇦',
  ),
  Country(name: 'Botswana', isoCode: 'BW', dialCode: '267', flag: '🇧🇼'),
  Country(name: 'Brazil', isoCode: 'BR', dialCode: '55', flag: '🇧🇷'),
  Country(
    name: 'British Virgin Islands',
    isoCode: 'VG',
    dialCode: '1284',
    flag: '🇻🇬',
  ),
  Country(name: 'Brunei', isoCode: 'BN', dialCode: '673', flag: '🇧🇳'),
  Country(name: 'Bulgaria', isoCode: 'BG', dialCode: '359', flag: '🇧🇬'),
  Country(name: 'Burkina Faso', isoCode: 'BF', dialCode: '226', flag: '🇧🇫'),
  Country(name: 'Burundi', isoCode: 'BI', dialCode: '257', flag: '🇧🇮'),
  Country(name: 'Cambodia', isoCode: 'KH', dialCode: '855', flag: '🇰🇭'),
  Country(name: 'Cameroon', isoCode: 'CM', dialCode: '237', flag: '🇨🇲'),
  Country(name: 'Canada', isoCode: 'CA', dialCode: '1', flag: '🇨🇦'),
  Country(name: 'Cape Verde', isoCode: 'CV', dialCode: '238', flag: '🇨🇻'),
  Country(
    name: 'Cayman Islands',
    isoCode: 'KY',
    dialCode: '1345',
    flag: '🇰🇾',
  ),
  Country(
    name: 'Central African Republic',
    isoCode: 'CF',
    dialCode: '236',
    flag: '🇨🇫',
  ),
  Country(name: 'Chad', isoCode: 'TD', dialCode: '235', flag: '🇹🇩'),
  Country(name: 'Chile', isoCode: 'CL', dialCode: '56', flag: '🇨🇱'),
  Country(name: 'China', isoCode: 'CN', dialCode: '86', flag: '🇨🇳'),
  Country(name: 'Colombia', isoCode: 'CO', dialCode: '57', flag: '🇨🇴'),
  Country(name: 'Comoros', isoCode: 'KM', dialCode: '269', flag: '🇰🇲'),
  Country(name: 'Congo (DRC)', isoCode: 'CD', dialCode: '243', flag: '🇨🇩'),
  Country(
    name: 'Congo (Republic)',
    isoCode: 'CG',
    dialCode: '242',
    flag: '🇨🇬',
  ),
  Country(name: 'Costa Rica', isoCode: 'CR', dialCode: '506', flag: '🇨🇷'),
  Country(name: 'Côte d’Ivoire', isoCode: 'CI', dialCode: '225', flag: '🇨🇮'),
  Country(name: 'Croatia', isoCode: 'HR', dialCode: '385', flag: '🇭🇷'),
  Country(name: 'Cuba', isoCode: 'CU', dialCode: '53', flag: '🇨🇺'),
  Country(name: 'Curaçao', isoCode: 'CW', dialCode: '599', flag: '🇨🇼'),
  Country(name: 'Cyprus', isoCode: 'CY', dialCode: '357', flag: '🇨🇾'),
  Country(name: 'Czechia', isoCode: 'CZ', dialCode: '420', flag: '🇨🇿'),
  Country(name: 'Denmark', isoCode: 'DK', dialCode: '45', flag: '🇩🇰'),
  Country(name: 'Djibouti', isoCode: 'DJ', dialCode: '253', flag: '🇩🇯'),
  Country(name: 'Dominica', isoCode: 'DM', dialCode: '1767', flag: '🇩🇲'),
  Country(
    name: 'Dominican Republic',
    isoCode: 'DO',
    dialCode: '1',
    flag: '🇩🇴',
  ),
  Country(name: 'Ecuador', isoCode: 'EC', dialCode: '593', flag: '🇪🇨'),
  Country(name: 'Egypt', isoCode: 'EG', dialCode: '20', flag: '🇪🇬'),
  Country(name: 'El Salvador', isoCode: 'SV', dialCode: '503', flag: '🇸🇻'),
  Country(
    name: 'Equatorial Guinea',
    isoCode: 'GQ',
    dialCode: '240',
    flag: '🇬🇶',
  ),
  Country(name: 'Eritrea', isoCode: 'ER', dialCode: '291', flag: '🇪🇷'),
  Country(name: 'Estonia', isoCode: 'EE', dialCode: '372', flag: '🇪🇪'),
  Country(name: 'Eswatini', isoCode: 'SZ', dialCode: '268', flag: '🇸🇿'),
  Country(name: 'Ethiopia', isoCode: 'ET', dialCode: '251', flag: '🇪🇹'),
  Country(name: 'Faroe Islands', isoCode: 'FO', dialCode: '298', flag: '🇫🇴'),
  Country(name: 'Fiji', isoCode: 'FJ', dialCode: '679', flag: '🇫🇯'),
  Country(name: 'Finland', isoCode: 'FI', dialCode: '358', flag: '🇫🇮'),
  Country(name: 'France', isoCode: 'FR', dialCode: '33', flag: '🇫🇷'),
  Country(name: 'French Guiana', isoCode: 'GF', dialCode: '594', flag: '🇬🇫'),
  Country(
    name: 'French Polynesia',
    isoCode: 'PF',
    dialCode: '689',
    flag: '🇵🇫',
  ),
  Country(name: 'Gabon', isoCode: 'GA', dialCode: '241', flag: '🇬🇦'),
  Country(name: 'Gambia', isoCode: 'GM', dialCode: '220', flag: '🇬🇲'),
  Country(name: 'Georgia', isoCode: 'GE', dialCode: '995', flag: '🇬🇪'),
  Country(name: 'Germany', isoCode: 'DE', dialCode: '49', flag: '🇩🇪'),
  Country(name: 'Ghana', isoCode: 'GH', dialCode: '233', flag: '🇬🇭'),
  Country(name: 'Gibraltar', isoCode: 'GI', dialCode: '350', flag: '🇬🇮'),
  Country(name: 'Greece', isoCode: 'GR', dialCode: '30', flag: '🇬🇷'),
  Country(name: 'Greenland', isoCode: 'GL', dialCode: '299', flag: '🇬🇱'),
  Country(name: 'Grenada', isoCode: 'GD', dialCode: '1473', flag: '🇬🇩'),
  Country(name: 'Guadeloupe', isoCode: 'GP', dialCode: '590', flag: '🇬🇵'),
  Country(name: 'Guam', isoCode: 'GU', dialCode: '1671', flag: '🇬🇺'),
  Country(name: 'Guatemala', isoCode: 'GT', dialCode: '502', flag: '🇬🇹'),
  Country(name: 'Guernsey', isoCode: 'GG', dialCode: '44', flag: '🇬🇬'),
  Country(name: 'Guinea', isoCode: 'GN', dialCode: '224', flag: '🇬🇳'),
  Country(name: 'Guinea-Bissau', isoCode: 'GW', dialCode: '245', flag: '🇬🇼'),
  Country(name: 'Guyana', isoCode: 'GY', dialCode: '592', flag: '🇬🇾'),
  Country(name: 'Haiti', isoCode: 'HT', dialCode: '509', flag: '🇭🇹'),
  Country(name: 'Honduras', isoCode: 'HN', dialCode: '504', flag: '🇭🇳'),
  Country(name: 'Hong Kong', isoCode: 'HK', dialCode: '852', flag: '🇭🇰'),
  Country(name: 'Hungary', isoCode: 'HU', dialCode: '36', flag: '🇭🇺'),
  Country(name: 'Iceland', isoCode: 'IS', dialCode: '354', flag: '🇮🇸'),
  Country(name: 'India', isoCode: 'IN', dialCode: '91', flag: '🇮🇳'),
  Country(name: 'Indonesia', isoCode: 'ID', dialCode: '62', flag: '🇮🇩'),
  Country(name: 'Iran', isoCode: 'IR', dialCode: '98', flag: '🇮🇷'),
  Country(name: 'Iraq', isoCode: 'IQ', dialCode: '964', flag: '🇮🇶'),
  Country(name: 'Ireland', isoCode: 'IE', dialCode: '353', flag: '🇮🇪'),
  Country(name: 'Isle of Man', isoCode: 'IM', dialCode: '44', flag: '🇮🇲'),
  Country(name: 'Israel', isoCode: 'IL', dialCode: '972', flag: '🇮🇱'),
  Country(name: 'Italy', isoCode: 'IT', dialCode: '39', flag: '🇮🇹'),
  Country(name: 'Jamaica', isoCode: 'JM', dialCode: '1876', flag: '🇯🇲'),
  Country(name: 'Japan', isoCode: 'JP', dialCode: '81', flag: '🇯🇵'),
  Country(name: 'Jersey', isoCode: 'JE', dialCode: '44', flag: '🇯🇪'),
  Country(name: 'Jordan', isoCode: 'JO', dialCode: '962', flag: '🇯🇴'),
  Country(name: 'Kazakhstan', isoCode: 'KZ', dialCode: '7', flag: '🇰🇿'),
  Country(name: 'Kenya', isoCode: 'KE', dialCode: '254', flag: '🇰🇪'),
  Country(name: 'Kiribati', isoCode: 'KI', dialCode: '686', flag: '🇰🇮'),
  Country(name: 'Kuwait', isoCode: 'KW', dialCode: '965', flag: '🇰🇼'),
  Country(name: 'Kyrgyzstan', isoCode: 'KG', dialCode: '996', flag: '🇰🇬'),
  Country(name: 'Laos', isoCode: 'LA', dialCode: '856', flag: '🇱🇦'),
  Country(name: 'Latvia', isoCode: 'LV', dialCode: '371', flag: '🇱🇻'),
  Country(name: 'Lebanon', isoCode: 'LB', dialCode: '961', flag: '🇱🇧'),
  Country(name: 'Lesotho', isoCode: 'LS', dialCode: '266', flag: '🇱🇸'),
  Country(name: 'Liberia', isoCode: 'LR', dialCode: '231', flag: '🇱🇷'),
  Country(name: 'Libya', isoCode: 'LY', dialCode: '218', flag: '🇱🇾'),
  Country(name: 'Liechtenstein', isoCode: 'LI', dialCode: '423', flag: '🇱🇮'),
  Country(name: 'Lithuania', isoCode: 'LT', dialCode: '370', flag: '🇱🇹'),
  Country(name: 'Luxembourg', isoCode: 'LU', dialCode: '352', flag: '🇱🇺'),
  Country(name: 'Macau', isoCode: 'MO', dialCode: '853', flag: '🇲🇴'),
  Country(
    name: 'North Macedonia',
    isoCode: 'MK',
    dialCode: '389',
    flag: '🇲🇰',
  ),
  Country(name: 'Madagascar', isoCode: 'MG', dialCode: '261', flag: '🇲🇬'),
  Country(name: 'Malawi', isoCode: 'MW', dialCode: '265', flag: '🇲🇼'),
  Country(name: 'Malaysia', isoCode: 'MY', dialCode: '60', flag: '🇲🇾'),
  Country(name: 'Maldives', isoCode: 'MV', dialCode: '960', flag: '🇲🇻'),
  Country(name: 'Mali', isoCode: 'ML', dialCode: '223', flag: '🇲🇱'),
  Country(name: 'Malta', isoCode: 'MT', dialCode: '356', flag: '🇲🇹'),
  Country(
    name: 'Marshall Islands',
    isoCode: 'MH',
    dialCode: '692',
    flag: '🇲🇭',
  ),
  Country(name: 'Martinique', isoCode: 'MQ', dialCode: '596', flag: '🇲🇶'),
  Country(name: 'Mauritania', isoCode: 'MR', dialCode: '222', flag: '🇲🇷'),
  Country(name: 'Mauritius', isoCode: 'MU', dialCode: '230', flag: '🇲🇺'),
  Country(name: 'Mayotte', isoCode: 'YT', dialCode: '262', flag: '🇾🇹'),
  Country(name: 'Mexico', isoCode: 'MX', dialCode: '52', flag: '🇲🇽'),
  Country(name: 'Micronesia', isoCode: 'FM', dialCode: '691', flag: '🇫🇲'),
  Country(name: 'Moldova', isoCode: 'MD', dialCode: '373', flag: '🇲🇩'),
  Country(name: 'Monaco', isoCode: 'MC', dialCode: '377', flag: '🇲🇨'),
  Country(name: 'Mongolia', isoCode: 'MN', dialCode: '976', flag: '🇲🇳'),
  Country(name: 'Montenegro', isoCode: 'ME', dialCode: '382', flag: '🇲🇪'),
  Country(name: 'Morocco', isoCode: 'MA', dialCode: '212', flag: '🇲🇦'),
  Country(name: 'Mozambique', isoCode: 'MZ', dialCode: '258', flag: '🇲🇿'),
  Country(name: 'Myanmar', isoCode: 'MM', dialCode: '95', flag: '🇲🇲'),
  Country(name: 'Namibia', isoCode: 'NA', dialCode: '264', flag: '🇳🇦'),
  Country(name: 'Nauru', isoCode: 'NR', dialCode: '674', flag: '🇳🇷'),
  Country(name: 'Nepal', isoCode: 'NP', dialCode: '977', flag: '🇳🇵'),
  Country(name: 'Netherlands', isoCode: 'NL', dialCode: '31', flag: '🇳🇱'),
  Country(name: 'New Caledonia', isoCode: 'NC', dialCode: '687', flag: '🇳🇨'),
  Country(name: 'New Zealand', isoCode: 'NZ', dialCode: '64', flag: '🇳🇿'),
  Country(name: 'Nicaragua', isoCode: 'NI', dialCode: '505', flag: '🇳🇮'),
  Country(name: 'Niger', isoCode: 'NE', dialCode: '227', flag: '🇳🇪'),
  Country(name: 'Nigeria', isoCode: 'NG', dialCode: '234', flag: '🇳🇬'),
  Country(name: 'Niue', isoCode: 'NU', dialCode: '683', flag: '🇳🇺'),
  Country(name: 'North Korea', isoCode: 'KP', dialCode: '850', flag: '🇰🇵'),
  Country(
    name: 'Northern Mariana Islands',
    isoCode: 'MP',
    dialCode: '1670',
    flag: '🇲🇵',
  ),
  Country(name: 'Norway', isoCode: 'NO', dialCode: '47', flag: '🇳🇴'),
  Country(name: 'Oman', isoCode: 'OM', dialCode: '968', flag: '🇴🇲'),
  Country(name: 'Pakistan', isoCode: 'PK', dialCode: '92', flag: '🇵🇰'),
  Country(name: 'Palestine', isoCode: 'PS', dialCode: '970', flag: '🇵🇸'),
  Country(name: 'Panama', isoCode: 'PA', dialCode: '507', flag: '🇵🇦'),
  Country(
    name: 'Papua New Guinea',
    isoCode: 'PG',
    dialCode: '675',
    flag: '🇵🇬',
  ),
  Country(name: 'Paraguay', isoCode: 'PY', dialCode: '595', flag: '🇵🇾'),
  Country(name: 'Peru', isoCode: 'PE', dialCode: '51', flag: '🇵🇪'),
  Country(name: 'Philippines', isoCode: 'PH', dialCode: '63', flag: '🇵🇭'),
  Country(name: 'Poland', isoCode: 'PL', dialCode: '48', flag: '🇵🇱'),
  Country(name: 'Portugal', isoCode: 'PT', dialCode: '351', flag: '🇵🇹'),
  Country(name: 'Puerto Rico', isoCode: 'PR', dialCode: '1', flag: '🇵🇷'),
  Country(name: 'Qatar', isoCode: 'QA', dialCode: '974', flag: '🇶🇦'),
  Country(name: 'Réunion', isoCode: 'RE', dialCode: '262', flag: '🇷🇪'),
  Country(name: 'Romania', isoCode: 'RO', dialCode: '40', flag: '🇷🇴'),
  Country(name: 'Russia', isoCode: 'RU', dialCode: '7', flag: '🇷🇺'),
  Country(name: 'Rwanda', isoCode: 'RW', dialCode: '250', flag: '🇷🇼'),
  Country(
    name: 'Saint Kitts and Nevis',
    isoCode: 'KN',
    dialCode: '1869',
    flag: '🇰🇳',
  ),
  Country(name: 'Saint Lucia', isoCode: 'LC', dialCode: '1758', flag: '🇱🇨'),
  Country(
    name: 'Saint Vincent & the Grenadines',
    isoCode: 'VC',
    dialCode: '1784',
    flag: '🇻🇨',
  ),
  Country(name: 'Samoa', isoCode: 'WS', dialCode: '685', flag: '🇼🇸'),
  Country(name: 'San Marino', isoCode: 'SM', dialCode: '378', flag: '🇸🇲'),
  Country(
    name: 'São Tomé & Príncipe',
    isoCode: 'ST',
    dialCode: '239',
    flag: '🇸🇹',
  ),
  Country(name: 'Saudi Arabia', isoCode: 'SA', dialCode: '966', flag: '🇸🇦'),
  Country(name: 'Senegal', isoCode: 'SN', dialCode: '221', flag: '🇸🇳'),
  Country(name: 'Serbia', isoCode: 'RS', dialCode: '381', flag: '🇷🇸'),
  Country(name: 'Seychelles', isoCode: 'SC', dialCode: '248', flag: '🇸🇨'),
  Country(name: 'Sierra Leone', isoCode: 'SL', dialCode: '232', flag: '🇸🇱'),
  Country(name: 'Singapore', isoCode: 'SG', dialCode: '65', flag: '🇸🇬'),
  Country(name: 'Slovakia', isoCode: 'SK', dialCode: '421', flag: '🇸🇰'),
  Country(name: 'Slovenia', isoCode: 'SI', dialCode: '386', flag: '🇸🇮'),
  Country(
    name: 'Solomon Islands',
    isoCode: 'SB',
    dialCode: '677',
    flag: '🇸🇧',
  ),
  Country(name: 'Somalia', isoCode: 'SO', dialCode: '252', flag: '🇸🇴'),
  Country(name: 'South Africa', isoCode: 'ZA', dialCode: '27', flag: '🇿🇦'),
  Country(name: 'South Korea', isoCode: 'KR', dialCode: '82', flag: '🇰🇷'),
  Country(name: 'South Sudan', isoCode: 'SS', dialCode: '211', flag: '🇸🇸'),
  Country(name: 'Spain', isoCode: 'ES', dialCode: '34', flag: '🇪🇸'),
  Country(name: 'Sri Lanka', isoCode: 'LK', dialCode: '94', flag: '🇱🇰'),
  Country(name: 'Sudan', isoCode: 'SD', dialCode: '249', flag: '🇸🇩'),
  Country(name: 'Suriname', isoCode: 'SR', dialCode: '597', flag: '🇸🇷'),
  Country(name: 'Sweden', isoCode: 'SE', dialCode: '46', flag: '🇸🇪'),
  Country(name: 'Switzerland', isoCode: 'CH', dialCode: '41', flag: '🇨🇭'),
  Country(name: 'Syria', isoCode: 'SY', dialCode: '963', flag: '🇸🇾'),
  Country(name: 'Taiwan', isoCode: 'TW', dialCode: '886', flag: '🇹🇼'),
  Country(name: 'Tajikistan', isoCode: 'TJ', dialCode: '992', flag: '🇹🇯'),
  Country(name: 'Tanzania', isoCode: 'TZ', dialCode: '255', flag: '🇹🇿'),
  Country(name: 'Thailand', isoCode: 'TH', dialCode: '66', flag: '🇹🇭'),
  Country(name: 'Timor-Leste', isoCode: 'TL', dialCode: '670', flag: '🇹🇱'),
  Country(name: 'Togo', isoCode: 'TG', dialCode: '228', flag: '🇹🇬'),
  Country(name: 'Tonga', isoCode: 'TO', dialCode: '676', flag: '🇹🇴'),
  Country(
    name: 'Trinidad & Tobago',
    isoCode: 'TT',
    dialCode: '1868',
    flag: '🇹🇹',
  ),
  Country(name: 'Tunisia', isoCode: 'TN', dialCode: '216', flag: '🇹🇳'),
  Country(name: 'Turkey', isoCode: 'TR', dialCode: '90', flag: '🇹🇷'),
  Country(name: 'Turkmenistan', isoCode: 'TM', dialCode: '993', flag: '🇹🇲'),
  Country(
    name: 'Turks & Caicos Islands',
    isoCode: 'TC',
    dialCode: '1649',
    flag: '🇹🇨',
  ),
  Country(name: 'Tuvalu', isoCode: 'TV', dialCode: '688', flag: '🇹🇻'),
  Country(name: 'Uganda', isoCode: 'UG', dialCode: '256', flag: '🇺🇬'),
  Country(name: 'Ukraine', isoCode: 'UA', dialCode: '380', flag: '🇺🇦'),
  Country(
    name: 'United Arab Emirates',
    isoCode: 'AE',
    dialCode: '971',
    flag: '🇦🇪',
  ),
  Country(name: 'United Kingdom', isoCode: 'GB', dialCode: '44', flag: '🇬🇧'),
  Country(name: 'United States', isoCode: 'US', dialCode: '1', flag: '🇺🇸'),
  Country(name: 'Uruguay', isoCode: 'UY', dialCode: '598', flag: '🇺🇾'),
  Country(name: 'Uzbekistan', isoCode: 'UZ', dialCode: '998', flag: '🇺🇿'),
  Country(name: 'Vanuatu', isoCode: 'VU', dialCode: '678', flag: '🇻🇺'),
  Country(name: 'Vatican City', isoCode: 'VA', dialCode: '39', flag: '🇻🇦'),
  Country(name: 'Venezuela', isoCode: 'VE', dialCode: '58', flag: '🇻🇪'),
  Country(name: 'Vietnam', isoCode: 'VN', dialCode: '84', flag: '🇻🇳'),
  Country(name: 'Yemen', isoCode: 'YE', dialCode: '967', flag: '🇾🇪'),
  Country(name: 'Zambia', isoCode: 'ZM', dialCode: '260', flag: '🇿🇲'),
  Country(name: 'Zimbabwe', isoCode: 'ZW', dialCode: '263', flag: '🇿🇼'),
];
